---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: interface
    template:
      src: "./config.j2"
      dest: "./configs/{{ inventory_hostname }}.cfg" 