---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    oneA: |
      you are
      the best football
      player in the
      world
    oneB: >
      you are
      the best football
      player in the
      world
    two:
      - one
      - two 
      - three
    three:
      one: 1
      two: 2
      three: 3
    four:
      - one: 11
        two: 22
        three: 33
      - abc: 44
        def: 55
        sgx: 66 

  tasks:
  # - name: show variables
  #   loop: "{{test_dict.each}}" # loop should get a list
  #   # with_items: "{{test_list}}" # loop should get a list
  #   # with_items: "{{test_dict.each}}" # loop should get a list
  #   # with_dict: "{{test_dict}}" # with_dict should get a dict | .key and .value format
  #   debug:
  #     # var: item.value[0].name
  #     var: item.name
  # - name: show current time
  #   stat: path=~/
  #   register: location
  - name: debug code
    # debug: msg="A debug message"
    # debug: var=someone  ###  "someone": "abc"
    # debug: msg="{{someone}}"  ###  "msg": "abc"
    # with_items: "{{four}}"
    # with_dict: "{{four}}"
    debug: var=oneB

      # var: sometwo # var: quote the variable directly
      # msg: "{{time}}" # msg: quote the variable with jinja syntax
      # msg: "{{location}}" 

    # when: right is defined