---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    one1: |
      you are
      the best football
      player in the
      world
    one2: >
      you are
      the best football
      player in the
      world
    one3:
      - one
      - two 
      - three
    one4:
      one: 1
      two: 2
      three: 3
    one5:
      - zero: 00
      - one: 11
        two: 22
        three: 33
      - abc: 44
        def: 55
        sgx: 66 
    one6:
      each:
      - name: f0/0
        ip: 10.0.1.1
        mask: 255.255.255.252
      - name: f0/1
        ip: 10.0.1.5
        mask: 255.255.255.252
      - name: lo0
        ip: 1.1.1.1
        mask: 255.255.255.255
      - name: lo1
        ip: 192.168.1.1
        mask: 255.255.255.0

  tasks:
  # - name: debug variables directly
  #   debug: var=one6.each.0.ip # parse the dict var once directly without loop function —— all in strateg
  #   debug: msg={{one6.each.0.ip}} # parse the dict var once directly without loop function —— all in strateg

  - name: debug variables with methods
    # with_dict: "{{one6}}" # parse the dict var once directly without loop function —— all in strategy
    # with_items: "{{one6.each}}" # parse the list var with loop function —— one by one strategy
    loop: "{{one6.each}}" # parse the list var with loop function —— one by one strategy
    # with_list: "{{one6.each}}" # parse the list var with loop function —— one by one strategy
    debug: var=item.ip
    # debug: msg={{item.ip}}