---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    someone: abc
    sometwo:
      - one
      - two 
      - three

  tasks:
  # - name: show variables
  #   loop: "{{test_dict.each}}" # loop should get a list
  #   # with_items: "{{test_list}}" # loop should get a list
  #   # with_items: "{{test_dict.each}}" # loop should get a list
  #   # with_dict: "{{test_dict}}" # with_dict should get a dict | .key and .value format
  #   debug:
  #     # var: item.value[0].name
  #     var: item.name
  - name: show current time
    command: uptime
    register: time
  - name: debug code
    # debug: msg="A debug message"
    # debug: var=someone  ###  "someone": "abc"
    # debug: msg="{{someone}}"  ###  "msg": "abc"
    debug:
      # var: sometwo # var: quote the variable directly
      # msg: "{{time}}" # msg: quote the variable with jinja syntax
      msg: "{{time}}" 
      # var: time