---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: show ip route
    ios_command:
      commands:
        - show ip route
      provider: "{{provider}}"
    register: route

  - name: show ip route result
    debug: 
      var: route.stdout.0

  - name: show ios_facts
    ios_facts: 
      provider: "{{provider}}"

  - name: show ansible_net_version
    debug: 
      var: ansible_net_version.stdout.0