---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ credential.username }}"
        password: "{{ credential.password }}"

  - name: show information
    ios_command:
      commands:
        - show ip route
      provider: "{{ provider }}"
    register: show

  - name: show above variable
    debug: 
      var: show 

  - name: show single
    debug: 
      var: ansible_net_version