---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: GET DATA
    ntc_show_command:
      # connection: offline
      # file: tests/cisco_nxos/cisco_nxos_show_version.raw
      # vendor: cisco_nxos
      # device_type: cisco_nxos
      platform: cisco_ios
      command: 'show version'
      # host: "{{ inventory_hostname }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
    # register:  mydata

  # - name: show ip route result
  #   debug: 
  #     var: route.stdout_lines.0

  # - name: save the routing result
  #   template:
  #     src: "./routing.j2"
  #     dest: "./results/{{inventory_hostname}}_routing.txt" 