---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: show ip route
    ntc_show_command:
      platform: cisco_ios
      command: 'sh ip route'
      host: "{{ inventory_hostname }}"
      template_dir: /root/.ansible/plugins/modules/ntc-ansible/ntc-templates/templates
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      use_templates: True