---
- name: default setting here
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Gather all legacy facts
    ios_facts:
      gather_subset: all
      provider: "{{provider}}"
  - name: show variable
    debug: var=ansible_net_interfaces