---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Gather all legacy facts
    ios_facts:
      gather_subset: all
      provider: "{{provider}}"
  - name: show variable
    debug: var= gather_subset