---
- hosts: all
  tasks:
    - name: napalm get_facts
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        dev_os: "{{os}}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        filter: "facts,interfaces,bgp_neighbors"
        # https://napalm.readthedocs.io/en/latest/support/index.html

      register: result

    - debug:
        var: result