---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: napalm get_facts
      napalm_get_facts:
        host: "{{ inventory_hostname }}"
        filter: facts,interfaces

    - debug:
        var: napalm_facts