---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: show ip route with ntc_show_command
    ntc_get_facts:
      platform: cisco_ios
      # command: 'show ip route'
      host: "{{ inventory_hostname }}"
      template_dir: /root/.ansible/plugins/modules/ntc-ansible/ntc-templates/templates
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
    register: routea

  # - name: show ip route standard
  #   ios_command:
  #     commands:
  #       - show ip route
  #     provider: "{{provider}}"
  #   register: routeb

  # # - name: show ip route result
  # #   debug: 
  # #     var: route.stdout_lines.0

  # - name: save the routing result
  #   template:
  #     src: "./routetable.j2"
  #     dest: "./results/{{inventory_hostname}}_routing.txt" 