---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: show ip route with ntc_show_command
    ntc_get_facts:
      platform: cisco_ios_ssh
      host: "{{ inventory_hostname }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
    register: routea

  # - name: show ip route standard
  #   ios_command:
  #     commands:
  #       - show ip route
  #     provider: "{{provider}}"
  #   register: routeb

  - name: show ip route result
    debug: 
      var: routea

  # - name: save the routing result
  #   template:
  #     src: "./routetable.j2"
  #     dest: "./results/{{inventory_hostname}}_routing.txt" 