---
- name: default setting
  hosts: r1
  connection: local
  gather_facts: no
  tasks:
  - name: show version
    ntc_show_command:
      platform: cisco_ios
      command: 'show version'
      host: "{{ inventory_hostname }}"
      # template_dir: /root/.ansible/plugins/modules/ntc-ansible/ntc-templates/templates
      template_dir: "{{ ntc_module_location }}/ntc-templates/templates"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
    register: routea

  # - name: show ip route standard
  #   ios_command:
  #     commands:
  #       - show ip route
  #     provider: "{{provider}}"
  #   register: routeb

  - name: show result
    debug: var= routea

  # - name: show ip route result
  #   debug: 
  #     var: routeb.stdout_lines
  # - name: save the routing result
  #   template:
  #     src: "./routetable.j2"
  #     dest: "./results/{{inventory_hostname}}_routing.txt" 