---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: napalm get_facts
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        dev_os: "{{os}}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        filter: facts,interfaces

    - debug:
        var: napalm_facts