---
- name: default setting
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: push configure
    ios_config:
      src: "./configs/{{inventory_hostname}}.cfg"
      provider: "{{provider}}"
      authorize: yes