---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: remove existing igp and bgp configure
    ios_config:
      lines:
        - no router isis
        - no router bgp {{bgp.as}}
      provider: "{{ provider }}"
      authorize: yes