---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: remove existing protocol config
    ios_config:
      lines:
        - no router isis
        - no router bgp {{bgp.as}}
        - no cdp run
      provider: "{{ provider }}"
      authorize: yes

  - name: remove existing interface config
    # ios_config:
    #   lines:
    #     - no ip address
    #     - shutdown
    #   parents: interface {{ item['name'] }}
    
    with_items: interfaces.each.stdout_lines
    register: var
  - name: show
  - debug: var
      # provider: "{{ provider }}"
      # authorize: yes