---
- hosts: ios
  connection: local
  gather_facts: no
  # strategy: free
  tasks:
  - name: remove existing protocol config
    ios_config:
      lines:
        - no router isis
        - no router bgp {{bgp.as}}
        - no cdp run
      provider: "{{ provider }}"
      authorize: yes

  - name: remove existing interface config
    loop: "{{interfaces.each}}"
    ios_config:
      lines:
        - no ip address
        - shutdown
      parents: interface {{ item['name'] }}     
      provider: "{{ provider }}"
      authorize: yes

  - name: save config
    ios_config:
      save_when: always
      provider: "{{ provider }}"
      authorize: yes
      